export declare const MAX_TX_VERSION = 2;
export declare const MAX_TX_SIZE: number;
export declare const MAX_BLOCK_WEIGHT: number;
export declare const MAX_TX_WEIGHT: number;
export declare const MAX_TX_SIGOPS: number;
export declare const MAX_TX_SIGOPS_COST: number;
export declare const BYTES_PER_SIGOP = 20;
export declare const MIN_RELAY = 1000;
export declare const BARE_MULTISIG = true;
export declare const FREE_THRESHOLD: number;
export declare const MAX_P2SH_SIGOPS = 15;
export declare const MAX_OP_RETURN_BYTES = 83;
export declare const MAX_OP_RETURN = 80;
export declare const MAX_P2WSH_STACK = 100;
export declare const MAX_P2WSH_PUSH = 80;
export declare const MAX_P2WSH_SIZE = 3600;
export declare const MEMPOOL_MAX_ANCESTORS = 25;
export declare const MEMPOOL_MAX_SIZE: number;
export declare const MEMPOOL_EXPIRY_TIME: number;
export declare const MEMPOOL_MAX_ORPHANS = 100;
export declare const MIN_BLOCK_WEIGHT = 0;
export declare const SIGNATURE_SIZE = 690;
export declare const PUBKEY_SIZE = 898;
export declare const PRIVKEY_SIZE = 1281;
export declare const BLOCK_PRIORITY_WEIGHT = 0;
export declare const BLOCK_PRIORITY_THRESHOLD: number;
export declare function getMinFee(size?: number, rate?: number): number;
export declare function getRoundFee(size?: number, rate?: number): number;
export declare function getRate(size: number, fee: number): number;
